app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/admin', function () {
   return view('admin.index');
});

Route::group(['middleware'=>'admin'], function() {
	Route::resource('/admin/users', 'AdminUsersController');
	Route::resource('/admin/posts', 'AdminPostsController');
	Route::resource('/admin/categories', 'AdminCategoriesController');
	Route::resource('/admin/media', 'AdminMediaController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = 	[
    	'category_id',
    	'photo_id',
    	'title',
    	'body'
    ];

    public function user () {
    	return $this->belongsTo('App\User');
    }

    public function photo () {
    	return $this->belongsTo('App\Photo');
    }

    public function category () {
    	return $this->belongsTo('App\Category');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Create Posts</h1>
	<div class="row">
	    {!! Form::open(['method'=>'POST', 'action'=>'AdminPostsController@store', 'files'=>true]) !!}
        <div class="form-group">
            {!! Form::label('title', 'Title:') !!}
            {!! Form::text('title', null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('category_id', 'Category:') !!}
            {!! Form::select('category_id', [''=>'Choose Categories'] + $categories, null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('photo_id', 'Photo:') !!}
            {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('body', 'Description:') !!}
            {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Create Post', ['class'=>'btn btn-primary']) !!}
        </div>
    	{!! Form::close() !!}
    </div>
    <div class="row">
    	@include('includes.form_error')
    </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Edit Posts</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-sm-9">
            <img class="text-center" width="400" src="{{URL::to('/')}}/images/{{$posts->photo ? $posts->photo->file : 'nophoto.png'}}" alt="">
        </div>

        <div class="col-sm-12">
            {!! Form::model($posts, ['method'=>'PATCH', 'action'=>['AdminPostsController@update', $posts->id], 'files'=>true]) !!}
            <div class="form-group">
                {!! Form::label('title', 'Title:') !!}
                {!! Form::text('title', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('category_id', 'Category:') !!}
                {!! Form::select('category_id', $categories, null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('photo_id', 'Photo:') !!}
                {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('body', 'Description:') !!}
                {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('Save', ['class'=>'btn btn-primary col-sm-6']) !!}
            </div>
            {!! Form::close() !!}
            {!! Form::open(['method'=>'DELETE', 'action'=>['AdminPostsController@destroy', $posts->id]]) !!}
                <div class="form-group">
                    {!! Form::submit('Delete Post', ['class'=>'btn btn-danger col-sm-6']) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
	<div class="row">
		@include('includes.form_error')
	</div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Posts</h1>
	<table class="table">
	  <tr>
	    <th>id</th>
	  	<th>photo_id</th>
	    <th>owner</th>
	    <th>category</th>
	    <th>title</th>
	    <th>body</th>
	    <th>created</th>
	    <th>updated</th>
	  </tr>
	  @if($posts)
	  	@foreach($posts as $post)
	  <tr>
	    <td>{{$post->id}}</td>
	  	<td><img width="50" src="{{URL::to('/')}}/images/{{$post->photo ? $post->photo->file : 'nophoto.png'}}" alt=""></td>
	    <td>{{$post->user->name}}</td>
	    <td>{{$post->category ? $post->category->name : 'Uncategorized'}}</td>
	    <td><a href="{{route('admin.posts.edit', $post->id)}}">{{$post->title}}</a></td>
	    <td>{{str_limit($post->body, 30)}}</td>
	    <td>{{$post->created_at->diffForhumans()}}</td>
	    <td>{{$post->updated_at->diffForhumans()}}</td>
	  </tr>
	  	@endforeach
	  @endif
	</table>
@endsection